GET http://localhost:7071/api/secop/contractType/arauca

<!--

GET http://localhost:7071/api/secop/municipalities/tolima/ibague

GET http://localhost:7071/api/secop/departments/tolima

GET http://localhost:7071/api/secop/contractor/tolima

GET http://localhost:7071/api/secop/entity/tolima     

GET http://localhost:7071/api/secop/processType/tolima

GET http://localhost:7071/api/secop/contractType/tolima

-->